// templates/marketingTemplateConfig.js

export const MarketingPDFTemplate = {
  meta: {
    version: "1.0",
    type: "marketing",
    title: "Marketing Strategy Report",
  },
  cover: {
    subtitle: "Generated by GetUniq AI",
    background: "gradient-purple",
  },
  sections: [
    { key: "overview", title: "Overview" },
    { key: "awareness", title: "Awareness Strategy" },
    { key: "consideration", title: "Consideration Strategy" },
    { key: "conversion", title: "Conversion Strategy" },
    { key: "deliverables", title: "Deliverables (List)" },
  ],
};
